### PR TITLE
updated MH reference and shifted headers

### PR DESCRIPTION
**Pull request by srwis**
i made minor tweaks that i was comfortable doing re issue: https://github.com/veg/datamonkey-js/issues/291#issue-621240272

### CODE REVIEW

**Comment by stevenweaver** [comment]
Thank you @srwis. Please let me know if there are any labels you need changed for the tutorial still that was not clear how to change.

**Comment by srwis** [comment]
I think we should go with the 1H, 2H, 3H, 3HSI, shorthand with float overs that say single hit, double hit, triple hit etc. that will be most consistent with the paper. 

actually i just saw where I can change most of these myself (https://github.com/veg/hyphy-vision/blob/c52f21cb2440085e0bbf8694649161a97ddba125/src/jsx/multihit.jsx#L143) so let me do that and resubmit the pull request. thanks for being patient.

**Comment by stevenweaver** [comment]
@srwis - I can merge, release, and deploy to datamonkey when you're ready. Nice!

**Comment by stevenweaver** [comment]
I can add site plot to scroll bar.

**Comment by srwis** [comment]
@stevenweaver yeah that was the last thing I was looking at figuring out. after that, I think it's good to go!

**Comment by stevenweaver** [comment]
Deployed. Thank you!

**Pull request merged**
