### PR TITLE
2.8.0 - rc

### PR DESCRIPTION
**Pull request by stevenweaver**

### CODE REVIEW

**Comment by stevenweaver** [comment]
Some issues with the library build. Hold off on merge for now.

**Comment by stephenshank** [comment]
Dear @stevenweaver,

Can you please add a commit with the `package.json` file that is generated after running:

```
yarn add react@16.12.0 react-dom@16.12.0
```

SLAC and MEME are currently broken (perhaps other pages as well) because I am using React Hooks in some components and libraries. They are nice, but experimental, and require matching versions of `react` and `react-dom` in all packages... something to keep in mind when dependabot comes knocking.

I can add this if you'd like, but I've checked that it resolves the issue and it seems to... didn't want to sneak commits on your PR.

Note this might be an issue when updating Datamonkey as well, but hopefully is also resolved with the same command.

Thanks,
Stephen

**Comment by stevenweaver** [comment]
Hi Stephen - you push commits. Thanks!

**Comment by stephenshank** [comment]
Downdating phylotree (undoing a dependabot commit) since the bump results in the tree component  rendering node labels twice:
image

**Pull request merged**
