### PR TITLE
adding slatkin maddison

### PR DESCRIPTION
**Pull request by stevenweaver**

### CODE REVIEW

**Comment by rdvelazquez** [comment]
Looks good! I made a few minor edits [here](https://github.com/veg/hyphy-vision/pull/190/commits/dc56122684919ff1168006a66f8686cade8cc51b).

I think "Found" should be something like "Tested" but I wasn't sure so I didn't change it:
Screen Shot 2019-03-19 at 6 31 31 AM

**Comment by stevenweaver** [comment]
Merging per internal discussion with @rdvelazquez and @stephenshank.

**Comment by stevenweaver** [comment]
Version `2.5.0-alpha` has been published.

**Comment by stevenweaver** [comment]
> Looks good! I made a few minor edits [here](https://github.com/veg/hyphy-vision/pull/190/commits/dc56122684919ff1168006a66f8686cade8cc51b).
> 
> I also converted the page to use the `ResultsPage` component to keep it more standardized with the other methods (see this [commit](https://github.com/veg/hyphy-vision/pull/190/commits/39acc138270e4c1be53ea72bde3b1dbe6d8fe2c6)). I also deleted the `template.jsx` component to avoid confusion in the future.
> 
> Should "Found" be something like "Tested"? I wasn't sure so I didn't change it:
> Screen Shot 2019-03-19 at 6 31 31 AM

Duly noted

**Pull request merged**
