### PR TITLE
2.1.5 rc

### PR DESCRIPTION
**Pull request by rdvelazquez**

### CODE REVIEW

**Comment by stevenweaver** [comment]
Dear @stephenshank, 

The `try/catch` appears to be due to requiring `csvexport` twice. I would recommend removing the `require` and using `import` and the `try/catch` would no longer be necessary. 

Best,
Steven

**Comment by rdvelazquez** [comment]
Thank you for the review @stephenshank and @stevenweaver. I thought removing the `require` would do the trick for not needing the try and catch... it works on vision.hyphy.org but the GUI fails webpacking with the following errors (I can't check it on datamonkey.org because I'm out of the office and thus not on our LAN). I say we just keep the try/catch statement but if anyone else want's to look into it more feel free.

`ERROR in ./node_modules/hyphy-vision/node_modules/jquery/dist/jquery.js
[0] Module build failed: Error: ENOENT: no such file or directory, open '/Users/ryanvelazquez/Documents/hyphy-gui/node_modules/hyphy-vision/node_modules/jquery/dist/jquery.js'
[0]  @ ./node_modules/hyphy-vision/dist/hyphyvision.js 3:179-196
[0]  @ ./src/components/results.jsx                                         
[0]  @ ./src/app.jsx
[0]  @ ./src/index.js                                                                                   
[0]                                                                            
[0] ERROR in ./node_modules/hyphy-vision/node_modules/phylotree/phylotree.js
[0] Module build failed: Error: ENOENT: no such file or directory, open '/Users/ryanvelazquez/Documents/hyphy-gui/node_modules/hyphy-vision/node_modules/phylotree/phylotree.js'
[0]  @ ./node_modules/hyphy-vision/dist/hyphyvision.js 3:157-177
[0]  @ ./src/components/results.jsx               
[0]  @ ./src/app.jsx
[0]  @ ./src/index.js
[0]
[0] ERROR in ./node_modules/hyphy-vision/node_modules/react-copy-to-clipboard/lib/index.js
[0] Module build failed: Error: ENOENT: no such file or directory, open '/Users/ryanvelazquez/Documents/hyphy-gui/node_modules/hyphy-vision/node_modules/react-copy-to-clipboard/lib/index.js'
[0]  @ ./node_modules/hyphy-vision/dist/hyphyvision.js 3:419-453                                    
[0]  @ ./src/components/results.jsx                                      
[0]  @ ./src/app.jsx
[0]  @ ./src/index.js                
[0]
[0] ERROR in ./node_modules/hyphy-vision/node_modules/react-dom/index.js
[0] Module build failed: Error: ENOENT: no such file or directory, open '/Users/ryanvelazquez/Documents/hyphy-gui/node_modules/hyphy-vision/node_modules/react-dom/index.js'
[0]  @ ./node_modules/hyphy-vision/dist/hyphyvision.js 3:83-103
[0]  @ ./src/components/results.jsx                                                                                
[0]  @ ./src/app.jsx          
[0]  @ ./src/index.js      
[0]             
[0] ERROR in ./node_modules/hyphy-vision/node_modules/react-json-view/dist/main.js
[0] Module build failed: Error: ENOENT: no such file or directory, open '/Users/ryanvelazquez/Documents/hyphy-gui/node_modules/hyphy-vision/node_modules/react-json-view/dist/main.js'
[0]  @ ./node_modules/hyphy-vision/dist/hyphyvision.js 3:455-481
[0]  @ ./src/components/results.jsx                                            
[0]  @ ./src/app.jsx        
[0]  @ ./src/index.js
[0]                                                                         
[0] ERROR in ./node_modules/hyphy-vision/node_modules/react-router-hash-link/lib/index.js
[0] Module build failed: Error: ENOENT: no such file or directory, open '/Users/ryanvelazquez/Documents/hyphy-gui/node_modules/hyphy-vision/node_modules/react-router-hash-link/lib/index.js'
[0]  @ ./node_modules/hyphy-vision/dist/hyphyvision.js 3:483-516               
[0]  @ ./src/components/results.jsx
[0]  @ ./src/app.jsx                 
[0]  @ ./src/index.js
[0]                                               
[0] ERROR in ./node_modules/hyphy-vision/node_modules/react-scrollchor/lib/scrollchor.js
[0] Module build failed: Error: ENOENT: no such file or directory, open '/Users/ryanvelazquez/Documents/hyphy-gui/node_modules/hyphy-vision/node_modules/react-scrollchor/lib/scrollchor.js'
[0]  @ ./node_modules/hyphy-vision/dist/hyphyvision.js 3:518-545
[0]  @ ./src/components/results.jsx                                     
[0]  @ ./src/app.jsx
[0]  @ ./src/index.js                                                                               
[0]                                                                      
[0] ERROR in ./node_modules/hyphy-vision/node_modules/react/react.js
[0] Module build failed: Error: ENOENT: no such file or directory, open '/Users/ryanvelazquez/Documents/hyphy-gui/node_modules/hyphy-vision/node_modules/react/react.js'
[0]  @ ./node_modules/hyphy-vision/dist/hyphyvision.js 3:27-43
[0]  @ ./src/components/results.jsx              
[0]  @ ./src/app.jsx
[0]  @ ./src/index.js
`

**Comment by stevenweaver** [comment]
Dear @rdvelazquez, 

I would say to remove it. Using both `require` and `import` leads to non-deterministic behavior, and the issue in `hyphy-gui` is downstream (needs to be resolved in `hyphy-gui`) of this package. 

Best,
Steven

**Comment by stephenshank** [comment]
Dear @rdvelazquez,

Please see my develop branch for a fix. Even upon deleting the `require`, I still found the `try`/`catch` block to be necessary to work on both vision and datamonkey. I do still believe it's an issue with the `csvexport` package; we had this at `^1.0.2`, which was resolving to `1.0.5`. [The entry file for the older version](https://github.com/edamtoft/CsvExport/blob/e5e4dd804c3b0d9d3428e7de039fc1b3c27946bb/source/Export.js) would attach the `CsvExport` object to the window. [The latest entry](https://github.com/edamtoft/CsvExport/blob/master/source/main.js) uses ES6, so I've bumped up to this. It now seems to work in both, without a `try`/`catch`.

Please confirm that this works for both standalone hyphy-vision and the GUI. If that's indeed the case, merging into this PR should be enough to close it.

Best,
Stephen

**Comment by rdvelazquez** [comment]
@stephenshank great catch! 

> Please confirm that this works for both standalone hyphy-vision and the GUI. If that's indeed the case, merging into this PR should be enough to close it.

I've confirmed that this works on both vision.hyphy.org as well as the GUI. I'll merge this in now. Thank you!

**Pull request merged**
