### PR TITLE
Json Data

### LINKED ISSUE #116: Update the JSON data included in the methods directory
When working on RELAX we noticed that the JSON data included with hyphy-vision was not in the format that datamonkey.org generates. The data sets included with hyphy-vision were uploaded in October 2017 and the HyPhy JSON fields were updated in December 2017 (http://hyphy.org/resources/json-fields.pdf). The JSON results provided in the methods folder should therefore be updated to make sure they follow the correct hyphy JSON results conventions.

### LINKED ISSUE #143: Consolidate all example results file to one location
All example files should reside in the `src` directory. Currently, we have example files in a directory called `test_files` and under `methods/**/*.json`, causing an unnecessary mental burden. Relates to #116.

### PR DESCRIPTION
**Pull request by rdvelazquez**
- Provides json data for the examples on vision.hyphy.org as well as additional json files for visual testing. 
 - Includes the input data and bash scripts for creating the json files.
 - Removes the `Methods` folder as this is no longer necessary with the single page app structure.
 - Moves the `test_data` directory as a subdirectory under the `data` folder.

We had previously discussed if the scripts for creating the json files should live in HyPhy rather than HyPhy-Vision but I am thinking that this is a better place, that way the json files will live in the same location as the input files and scripts that created them.

Closes #116 and Closes #143 .

### CODE REVIEW

**Comment by rdvelazquez** [comment]
> Navbar appears to be broken.
> Missing FASTA files.

Yep. This pull request is for the json data. Those two issues are related to the partially completed bootstrap upgrade. See #141.

**Comment by stevenweaver** [comment]
Dear @rdvelazquez, 

Ok, I see. I'm not sure if this was the intention, but if there is another feature we want to merge into develop, then we should branch off of develop and not merge in other pending features. 

I'm going to mark this PR as being blocked by #141. 

Best,
Steven

**Comment by rdvelazquez** [comment]
> I'm going to mark this PR as being blocked by #141.

@stevenweaver and/or @stephenshank. #141 has been merged. This is now ready for review.

**Comment by stevenweaver** [comment]
Very nice work

**Pull request merged**
