### PR TITLE
adding npm deploy to travis

### PR DESCRIPTION
**Pull request by stevenweaver**

### CODE REVIEW

**Comment by rdvelazquez** [comment]
This looks great! You should probably also update the `README.md` in hyphy-vision and the `releasing-hyphy-vision.md` in operations documentation to reflect the new release procedures.

**Comment by stevenweaver** [comment]
I agree. Thanks for the reminder. We still need to make sure this works though! We won't know until we're ready to deploy the next version!

**Comment by rdvelazquez** [comment]
>We won't know until we're ready to deploy the next version!

Yep. Fingers crossed. If it does work we should do the same for all our other packages. I also want to look into some sort of "push-to-deploy" for our websites.

**Comment by rdvelazquez** [comment]
@stevenweaver FYI - When I bumped the version to 2.1.0 travis didn't automatically deploy to npm. I think this was because I tagged the release after the commit where I bumped the version (next release we should try tagging it prior to pushing-to/merging-into veg master.

**Pull request merged**
