### PR TITLE
FADE

### PR DESCRIPTION
**Pull request by rdvelazquez**

### CODE REVIEW

**Comment by rdvelazquez** [comment]
@sjspielman, @spond or @stevenweaver I know the FADE method is still under development but do we have an example dataset of json results file that shows significant results and/or would be a good example to use for developing the viz page?

**Comment by rdvelazquez** [comment]
@sjspielman simulation data would be great. Can you email it to me at ryan.velazquez0001@temple.edu? If it's on the cluster you can just send links or tell me where it is.
Thanks!

**Comment by sjspielman** [comment]
@rdvelazquez I had saved all simulations in the silverback directory `/data/shares/projects/FADE` but it seems like `/data/` no longer contains project data - 
```
[sjspielman@silverback ~]$ cd /data/
[sjspielman@silverback data]$ ls -la
total 4
drwxr-xr-x.  2 root root    6 May 24 16:56 .
dr-xr-xr-x. 21 root root 4096 Oct  1 10:00 ..
```
Possibly something changed on the cluster since the summer and files were moved, maybe check with @stevenweaver?

**Comment by rdvelazquez** [comment]
`/data/shares` has been down for a bit (hardware issues). Now that I know where the simulation data is I should be good once we get `/data/shares` back up.
Thanks @sjspielman

**Comment by rdvelazquez** [comment]
This is now ready for review. There are improvements that could be made but the page has already been useful to me for evaluating results and it would probably be good to get this merged in.

__Highlight:__

Interacitve Summary:
fade-summary

Customizable Graph:
fade-graph

Dynamic Table:
fade-table

Improvements that could be made that I'm aware of (for reference later):
- Highlighting the tested/background branches on the tree
- Showing the site index when hovering over the points on the graph
- Allowing the graph to meaningfully show data for all the amino acids
- Smoothing out some kinks with scroll position and the dynamic nature of the page (i.e. the scroll position can jump a bit when selecting/unselecting the "Any" amino acid button)

**Comment by spond** [comment]
Dear @rdvelazquez,

This looks very cool. I'll pull your code and give review tonight.

Best,
Sergei

**Pull request merged**
